services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgbouncer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT_NUMBER: 5432
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - 6432:6432
    depends_on:
      - db
